version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
  reviewers:
  - lusoalex
  assignees:
  - lusoalex
  ignore:
  - dependency-name: io.vertx:vertx-core
    versions:
    - 3.7.1
